version: '3.0'
services:
  node:
    image: "node:latest"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: "npm run start:prod"