version: '1.0'
services:
  node:
    image: "node:latest"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command: "npm run start:prod"